### PR TITLE
Eaglerrinth Dark Design, User Profiles, Better CSS, animations, and Categories

### PR DESCRIPTION
**Pull request by SpeedSlicer**

### CODE REVIEW

**Comment by SpeedSlicer** [comment]
Most commits are a whole lot of nothingness

**Review by slendemenrockskill1 — APPROVED** [review]
pls see

**Comment by SpeedSlicer** [comment]
> > Great
> 
> why did u approve yourself using your alt?

I did something stupid on my school chromebook and thought it was a diff pull request after i renamed it

**Comment by SpeedSlicer** [comment]
> @SpeedSlicer
> 
> > Add Resource Packs
> 
> just use minexlauncher resource packs

what i need to do is make uploading mods and resource packs first

**Comment by SpeedSlicer** [comment]
after this gets merged

**Comment by radmanplays** [comment]
@SpeedSlicer can you remove or resize the red thingy behind the download and view source buttons?
image

also the favicon is broken

main eaglerrinth repo:
image

your fork:
image

**Comment by OtterCodes101** [comment]
lgtm

**Pull request merged**
