### PR TITLE
Eaglerrinth Dark Design, User Profiles, Better CSS, animations, and Categories

### PR DESCRIPTION
**Pull request by leahanderson1**
recreation of @SpeedSlicer 's PR

### CODE REVIEW

**Comment by OtterCodes101** [comment]
image

**Comment by SpeedSlicer** [comment]
alr im gonna do it

**Comment by SpeedSlicer** [comment]
Done

**Comment by SpeedSlicer** [comment]
added sort by api and orginization

**Comment by SpeedSlicer** [comment]
plus updates to the user page

**Review by GavinGoGaming — APPROVED** [review]
good, but id default view source to an alert or just disable the button as of rn it just loops back to the root url

**Comment by SpeedSlicer** [comment]
Added eaglerforge injector and navbar

**Comment by OtterCodes101** [comment]
> Added eaglerforge injector and navbar

don't add injector just add a link to the normal one that way its easier to update smh

**Comment by SpeedSlicer** [comment]
alr

**Comment by SpeedSlicer** [comment]
?

**Pull request merged**
